service: auth-serverless1

provider: 
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements: 
        - Effect: Allow 
          Action:
          - cognito-idp:AdminGetUser
          Resource: arn:aws:cognito-idp:us-east-1:381491854638:userpool/us-east-1_gnDA7HJkq
        - Effect: Allow
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          Resource: arn:aws:ssm:us-east-1:381491854638:parameter/prod-*


functions:
  registerUser:
    handler: register.registerUser
    events: 
      - http:
          path: register
          method: post 
          cors: true

  getUserInfo:
    handler: getUserInfo.GetUserInfo
    events:
      - http:
          path: getUserInfo
          method: post
          cors: true
  
  loginUser:
    handler: login.loginUser
    events:
      - http:
         path: login
         method: post
         cors: true
    
  
  customMessage:
    handler: customMessage.customMessage
    events:
      - http:
          path: customMessage
          method: post
          cors: true

  forgotPassword:
    handler: forgotPassword.handler
    events:
      - http:
          path: forgotPassword
          method: post
          cors: true
    

  confirmNewPassword:
    handler: confirmNewPassword.handler
    events:
      - http:
          path: confirmNewPassword
          method: post
          cors: true